language: python
python:
  - "3.4"
  - "3.3"
  - "3.2"
  - "2.7"
  - "2.6"
services:
  - mongodb
  - postgresql
before_install:
  - "sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 7F0CEB10"
  - "echo 'deb http://downloads-distro.mongodb.org/repo/ubuntu-upstart dist 10gen' | sudo tee /etc/apt/sources.list.d/mongodb.list"
  - "sudo apt-get update"
  - "sudo apt-get install mongodb-org-server"
  - "sudo apt-get install python2.7-dev python3-dev"
install: 
  - pip install -r requirements.txt
# # command to run tests, e.g. python setup.py test
script:
  - python manager.py syncdb
  - python manager.py test
